# Generated by Django 4.2.4 on 2023-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ManageCustomUsersApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("address", models.TextField()),
            ],
        ),
    ]
