# Generated by Django 4.2.4 on 2023-08-06 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ManageCustomUsersApp", "0002_linkdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomGroup",
        ),
        migrations.DeleteModel(
            name="CustomPermission",
        ),
    ]
